const bittrex_currencies = {
  BTC: 'Bitcoin',
  LTC: 'Litecoin',
  DOGE: 'Dogecoin',
  VTC: 'Vertcoin',
  PPC: 'Peercoin',
  FTC: 'Feathercoin',
  RDD: 'ReddCoin',
  NXT: 'NXT',
  DASH: 'Dash',
  POT: 'PotCoin',
  BLK: 'BlackCoin',
  EMC2: 'Einsteinium',
  XMY: 'Myriad',
  GLC: 'GoldCoin',
  GRS: 'Groestlcoin',
  NLG: 'Gulden',
  MONA: 'MonaCoin',
  THC: 'HempCoin',
  VRC: 'VeriCoin',
  CURE: 'CureCoin',
  XMR: 'Monero',
  XDN: 'DigitalNote',
  NAV: 'NAVCoin',
  XST: 'Stealth',
  VIA: 'ViaCoin',
  PINK: 'PinkCoin',
  IOC: 'I/OCoin',
  SYS: 'SysCoin',
  DGB: 'DigiByte',
  BTS: 'BitShares',
  BURST: 'BURST',
  EXCL: 'ExclusiveCoin',
  BLOCK: 'Blocknet',
  ABY: 'ArtByte',
  XRP: 'XRP',
  GAME: 'GameCredits',
  NXS: 'Nexus',
  XCP: 'Counterparty',
  XVG: 'Verge',
  GEO: 'GeoCoin',
  FLDC: 'FoldingCoin',
  FLO: 'FLO',
  XEM: 'NEM',
  MUE: 'MonetaryUnit',
  GAM: 'Gambit',
  SPHR: 'Sphere',
  OK: 'OkCash',
  AEON: 'Aeon',
  ETH: 'Ethereum',
  EXP: 'Expanse',
  OMNI: 'OmniCoin',
  USDT: 'Tether',
  AMP: 'SynereoAmp',
  XLM: 'Lumen',
  RVR: 'RevolutionVR',
  EMC: 'EmerCoin',
  FCT: 'Factom',
  MAID: 'MaidSafeCoin',
  SLS: 'SaluS',
  RADS: 'Radium',
  DCR: 'Decred',
  PIVX: 'Pivx',
  MEME: 'Memetic',
  STEEM: 'STEEM',
  LSK: 'Lisk',
  DGD: 'DigixDAO',
  WAVES: 'Waves',
  LBC: 'LBRY Credits',
  SBD: 'SteemDollars',
  ETC: 'Ethereum Classic',
  STRAT: 'Stratis',
  VRM: 'Verium',
  REP: 'Augur',
  SHIFT: 'Shift',
  ARDR: 'Ardor',
  XZC: 'ZCoin',
  NEO: 'Neo',
  ZEC: 'ZCash',
  UBQ: 'Ubiq',
  KMD: 'Komodo',
  SIB: 'Sibcoin',
  ION: 'Ion',
  CRW: 'Crown',
  SWT: 'Swarm City Token',
  MLN: 'Melon',
  ARK: 'Ark',
  DYN: 'Dynamic',
  INCNT: 'Incent',
  GBYTE: 'Bytes',
  GNT: 'Golem',
  NXC: 'Nexium',
  EDG: 'Edgeless',
  MORE: 'More',
  WINGS: 'Wings DAO',
  RLC: 'iEx.ec',
  GNO: 'Gnosis',
  GUP: 'Guppy',
  HMQ: 'Humaniq',
  ANT: 'Aragon',
  ZEN: 'Horizen',
  SC: 'Siacoin',
  BAT: 'Basic Attention Token',
  '1ST': 'Firstblood',
  QRL: 'Quantum Resistant Ledger',
  PTOY: 'Patientory',
  BNT: 'Bancor',
  NMR: 'Numeraire',
  SNT: 'Status Network Token',
  DCT: 'DECENT',
  XEL: 'XEL',
  MCO: 'MCO',
  ADT: 'adToken',
  FUN: 'FunFair',
  PAY: 'TenX Pay Token',
  MTL: 'METAL',
  STORJ: 'STORJ',
  ADX: 'AdEx',
  OMG: 'OmiseGO',
  CVC: 'Civic',
  PART: 'Particl',
  QTUM: 'Qtum',
  BCH: 'Bitcoin Cash (ABC)',
  DNT: 'district0x',
  ADA: 'Cardano',
  MANA: 'Decentraland',
  SALT: 'Salt',
  TIX: 'Blocktix',
  RCN: 'Ripio Credit Network',
  VIB: 'Viberate',
  MER: 'Mercury',
  POWR: 'PowerLedger',
  ENG: 'Enigma',
  UKG: 'UnikoinGold',
  IGNIS: 'Ignis',
  SRN: 'Sirin Token',
  WAXP: 'WAXP',
  ZRX: '0x Protocol',
  VEE: 'BLOCKv',
  BCPT: 'BlockMason Credit Protocol',
  TRX: 'Tron',
  TUSD: 'TrueUSD',
  LRC: 'Loopring',
  UP: 'UpToken',
  DMT: 'DMarket',
  POLY: 'Polymath',
  PRO: 'Propy',
  BLT: 'Bloom',
  STORM: 'Storm',
  AID: 'AidCoin',
  NGC: 'Naga',
  GTO: 'Gifto',
  OCN: 'Odyssey',
  USD: 'US Dollar',
  TUBE: 'BitTube',
  CBC: 'CashBet',
  CMCT: 'Crowd Machine',
  NLC2: 'NoLimitCoin',
  BKX: 'Bankex',
  MFT: 'Mainframe',
  LOOM: 'Loom Network',
  RFR: 'Refereum',
  RVN: 'RavenCoin',
  BFT: 'BnkToTheFuture',
  GO: 'GoChain',
  HYDRO: 'Hydro',
  UPP: 'Sentinel Protocol',
  ENJ: 'Enjin',
  MET: 'Metronome',
  DTA: 'Data',
  EDR: 'Endor',
  BOXX: 'Blockparty',
  IHT: 'I-House Token',
  XHV: 'Haven Protocol',
  PMA: 'PumaPay',
  PAL: 'PAL Network',
  PAX: 'Paxos Standard',
  MOC: 'Mossland',
  SPC: 'SpaceChain',
  BSV: 'Bitcoin SV',
  XNK: 'Ink Protocol',
  SOLVE: 'Solve.Care',
  USDS: 'StableUSD',
  LBA: 'Cred',
  MOBI: 'Mobius',
  BTM: 'Bytom',
  SPND: 'Spendcoin',
  DAI: 'Dai',
  HBAR: 'Hedera Hashgraph'
};

export default bittrex_currencies;

